# Base configs
#baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Art by Mrunal Joshi"
subtitle: "See the world through my eyes!"
author: "Mrunal Joshi"
header:
 title: "Art"
 subtitle: "by Mrunal Joshi"
footer:
 name: "Hey there, my name is Mrunal"
 bio: "Interior designer"
web_design: "AJ"
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  #twitter: "https://www.twitter.com/ram__patra"
  #instagram: "https://www.instagram.com/ram_patra"
  #linkedin: "https://in.linkedin.com/in/ram-patra"
